// flow-typed signature: ce5ddb2fa18974ee5f013d3f44eb65ce
// flow-typed version: <<STUB>>/changeset-map_v1.0.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'changeset-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'changeset-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'changeset-map/dist/bundle' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/config' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/getChangeset' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/helpers' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/index' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/map' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/propsDiff' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/query' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/render' {
  declare module.exports: any;
}

declare module 'changeset-map/lib/sidebar' {
  declare module.exports: any;
}

declare module 'changeset-map/public/bundle' {
  declare module.exports: any;
}

declare module 'changeset-map/rollup.plugin.config' {
  declare module.exports: any;
}

declare module 'changeset-map/rollup.website.config' {
  declare module.exports: any;
}

declare module 'changeset-map/www/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'changeset-map/dist/bundle.js' {
  declare module.exports: $Exports<'changeset-map/dist/bundle'>;
}
declare module 'changeset-map/lib/config.js' {
  declare module.exports: $Exports<'changeset-map/lib/config'>;
}
declare module 'changeset-map/lib/getChangeset.js' {
  declare module.exports: $Exports<'changeset-map/lib/getChangeset'>;
}
declare module 'changeset-map/lib/helpers.js' {
  declare module.exports: $Exports<'changeset-map/lib/helpers'>;
}
declare module 'changeset-map/lib/index.js' {
  declare module.exports: $Exports<'changeset-map/lib/index'>;
}
declare module 'changeset-map/lib/map.js' {
  declare module.exports: $Exports<'changeset-map/lib/map'>;
}
declare module 'changeset-map/lib/propsDiff.js' {
  declare module.exports: $Exports<'changeset-map/lib/propsDiff'>;
}
declare module 'changeset-map/lib/query.js' {
  declare module.exports: $Exports<'changeset-map/lib/query'>;
}
declare module 'changeset-map/lib/render.js' {
  declare module.exports: $Exports<'changeset-map/lib/render'>;
}
declare module 'changeset-map/lib/sidebar.js' {
  declare module.exports: $Exports<'changeset-map/lib/sidebar'>;
}
declare module 'changeset-map/public/bundle.js' {
  declare module.exports: $Exports<'changeset-map/public/bundle'>;
}
declare module 'changeset-map/rollup.plugin.config.js' {
  declare module.exports: $Exports<'changeset-map/rollup.plugin.config'>;
}
declare module 'changeset-map/rollup.website.config.js' {
  declare module.exports: $Exports<'changeset-map/rollup.website.config'>;
}
declare module 'changeset-map/www/index.js' {
  declare module.exports: $Exports<'changeset-map/www/index'>;
}
