// flow-typed signature: 7fec69e7905ef366dc0740ab4848c7e6
// flow-typed version: <<STUB>>/date-input-polyfill_v^2.14.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-input-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-input-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-input-polyfill/date-input-polyfill.dist' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/date-input-polyfill' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/dateformat' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/input' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/locales' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/picker' {
  declare module.exports: any;
}

declare module 'date-input-polyfill/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-input-polyfill/date-input-polyfill.dist.js' {
  declare module.exports: $Exports<
    'date-input-polyfill/date-input-polyfill.dist'
  >;
}
declare module 'date-input-polyfill/date-input-polyfill.js' {
  declare module.exports: $Exports<'date-input-polyfill/date-input-polyfill'>;
}
declare module 'date-input-polyfill/dateformat.js' {
  declare module.exports: $Exports<'date-input-polyfill/dateformat'>;
}
declare module 'date-input-polyfill/input.js' {
  declare module.exports: $Exports<'date-input-polyfill/input'>;
}
declare module 'date-input-polyfill/locales.js' {
  declare module.exports: $Exports<'date-input-polyfill/locales'>;
}
declare module 'date-input-polyfill/picker.js' {
  declare module.exports: $Exports<'date-input-polyfill/picker'>;
}
declare module 'date-input-polyfill/webpack.config.js' {
  declare module.exports: $Exports<'date-input-polyfill/webpack.config'>;
}
