// flow-typed signature: f6e4789e05dc9b5f947620d4f89d6d13
// flow-typed version: <<STUB>>/react-anchorify-text_v^2.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-anchorify-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-anchorify-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-anchorify-text/example/app' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/karma.conf' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/lib/components/AnchorifyText' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/lib/index' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/src/components/AnchorifyText' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/src/index' {
  declare module.exports: any;
}

declare module 'react-anchorify-text/test/components/AnchorifyText_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-anchorify-text/example/app.js' {
  declare module.exports: $Exports<'react-anchorify-text/example/app'>;
}
declare module 'react-anchorify-text/karma.conf.js' {
  declare module.exports: $Exports<'react-anchorify-text/karma.conf'>;
}
declare module 'react-anchorify-text/lib/components/AnchorifyText.js' {
  declare module.exports: $Exports<
    'react-anchorify-text/lib/components/AnchorifyText'
  >;
}
declare module 'react-anchorify-text/lib/index.js' {
  declare module.exports: $Exports<'react-anchorify-text/lib/index'>;
}
declare module 'react-anchorify-text/src/components/AnchorifyText.js' {
  declare module.exports: $Exports<
    'react-anchorify-text/src/components/AnchorifyText'
  >;
}
declare module 'react-anchorify-text/src/index.js' {
  declare module.exports: $Exports<'react-anchorify-text/src/index'>;
}
declare module 'react-anchorify-text/test/components/AnchorifyText_spec.js' {
  declare module.exports: $Exports<
    'react-anchorify-text/test/components/AnchorifyText_spec'
  >;
}
