// flow-typed signature: 2ebe4ce4f57bbef0c9b56e7b0b96a7f0
// flow-typed version: <<STUB>>/react-app-rewired_v^1.0.5/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewired'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewired' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-rewired/bin/index' {
  declare module.exports: any;
}

declare module 'react-app-rewired/config-overrides' {
  declare module.exports: any;
}

declare module 'react-app-rewired/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'react-app-rewired/config/paths' {
  declare module.exports: any;
}

declare module 'react-app-rewired/config/polyfills' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/build' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/start' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/test' {
  declare module.exports: any;
}

declare module 'react-app-rewired/utils/createJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-rewired/bin/index.js' {
  declare module.exports: $Exports<'react-app-rewired/bin/index'>;
}
declare module 'react-app-rewired/config-overrides.js' {
  declare module.exports: $Exports<'react-app-rewired/config-overrides'>;
}
declare module 'react-app-rewired/config/jest/babelTransform.js' {
  declare module.exports: $Exports<
    'react-app-rewired/config/jest/babelTransform'
  >;
}
declare module 'react-app-rewired/config/paths.js' {
  declare module.exports: $Exports<'react-app-rewired/config/paths'>;
}
declare module 'react-app-rewired/config/polyfills.js' {
  declare module.exports: $Exports<'react-app-rewired/config/polyfills'>;
}
declare module 'react-app-rewired/scripts/build.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/build'>;
}
declare module 'react-app-rewired/scripts/start.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/start'>;
}
declare module 'react-app-rewired/scripts/test.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/test'>;
}
declare module 'react-app-rewired/utils/createJestConfig.js' {
  declare module.exports: $Exports<'react-app-rewired/utils/createJestConfig'>;
}
