name: Feature request
description: Suggest a new feature for OSMCha
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: feature-value
    attributes:
      label: Why would this be useful to you or other users?
    validations:
      required: true
