name: Build Docker Image, Push to GHCR

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for production
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/osmcha/osmcha-frontend:latest
          ghcr.io/osmcha/osmcha-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Docker image for test instance at osmcha-test.ds.io
      uses: docker/build-push-action@v4
      with:
        # Pass the build environment as a build argument. Ensures that the correct
        # hostname is used in the frontend.
        # Todo: There's probably a better way to do this than building separate images
        build-args: BUILD_ENV=test
        context: .
        push: true
        tags: |
          ghcr.io/osmcha/osmcha-frontend-test:latest
          ghcr.io/osmcha/osmcha-frontend-test:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max